Django/ECS_GUI/ECS_GUI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("GUI.urls")),
    path('admin/', admin.site.urls),
]

Django/ECS_GUI/GUI/urls.py
from django.urls import path
from django.conf.urls import include

from . import views

app_name='GUI'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index.as_view(), name='index'),
    path('pca/<str:pcaId>', views.pcaView.as_view(), name='pca'),
    path('createPartition/', views.create_pca.as_view(), name='create_pca'),
    path('deletePartition/',views.delete_pca.as_view(), name='delete_pca'),
    path('createDetector/', views.create_detector.as_view(), name='create_detector'),
    path('deleteDetectors', views.deleteDetector.as_view(), name='delete_detectors'),
    path('moveDetectors', views.moveDetectors.as_view(), name="move_detectors"),
    path('ready/<str:pcaId>', views.ready.as_view(), name='ready'),
    path('start/<str:pcaId>', views.start.as_view(), name='start'),
    path('stop/<str:pcaId>', views.stop.as_view(), name='stop'),
    path('abort/<str:pcaId>', views.abort.as_view(), name='abort'),
    path('reset/<str:pcaId>', views.reset.as_view(), name='reset'),
    path('getDetectorListForPca/',views.getDetectorListForPCA,name='getDetectorListForPCA'),
    path('currentTableAndLogRequest/<str:pcaId>',views.currentTableAndLogRequest,name='currentTableAndLogRequest'),
    path('take_pca_control/<str:pcaId>/<str:targetPage>', views.takePCAControl, name='take_pca_control'),
    path('giveup_pca_control/<str:pcaId>/<str:targetPage>', views.giveUpPCAControl, name='giveup_pca_control'),
    path('take_ecs_control/<str:targetPage>', views.takeECSControl, name='take_ecs_control'),
    path('giveup_ecs_control/<str:targetPage>', views.giveUpECSControl, name='giveup_ecs_control'),
    path('configureTagModal/<str:pcaId>', views.configTagModalView.as_view(), name="configureTagModal"),
    path('getConfigsForTag/', views.getConfigsForTag, name="getConfigsForTag"),
    path('getConfigsForSystem/', views.getConfigsForSystem, name="getConfigsForSystem"),
    path('editConfiguration/', views.editConfiguration.as_view(), name="editConfiguration"),
    path('editConfigurationTag/', views.editConfigurationTag.as_view(), name="editConfigurationTag"),
    path('clients/',views.clientPage.as_view(), name='clients'),
]

Django/ECS_GUI/GUI/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
import datetime
from django.conf import settings

class pcaModel(models.Model):
    """holds timestamp and permission for a pca"""
    id = models.CharField(max_length=200, primary_key=True)
    permissionTimestamp = models.DateTimeField(null=True)

    def __str__(self):
        return self.id
    class Meta:
        permissions = (
                        ("can_take_pca_control", "can take pca control"),
                        ("has_pca_control", "has taken control"),
                      )

class ecsModel(models.Model):
    """holds timestamp and permission for the ecs"""
    id = models.CharField(max_length=200, primary_key=True)
    permissionTimestamp = models.DateTimeField(null=True)

    def __str__(self):
        return self.id
    class Meta:
        permissions = (
                        ("can_take_ecs_control", "can take ecs control"),
                        ("has_ecs_control", "has taken control"),
                      )

User = settings.AUTH_USER_MODEL

class LoggedInUser(models.Model):
    """creates an association between a session key and an user"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='logged_in_user')
    # Session keys are 32 characters long
    session_key = models.CharField(max_length=32, null=True, blank=True)

    def __str__(self):
        return self.user.username

Django/ECS_GUI/GUI/views.py
from django.shortcuts import get_object_or_404,render,redirect
from guardian.shortcuts import assign_perm, get_users_with_perms, remove_perm, get_user_perms
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from GUI.models import pcaModel, LoggedInUser, ecsModel
from django.urls import reverse
from django.conf import settings
import json
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission
from django.apps import apps
import threading
import time
from django.utils import timezone
from django import forms
import sys

projectPath = settings.PATH_TO_PROJECT
sys.path.append(projectPath)
from ECSCodes import ECSCodes
codes = ECSCodes()
from DataObjects import DataObjectCollection, detectorDataObject, partitionDataObject, stateObject, configObject
from ECA import ECA

eca = ECA()

gui = apps.get_app_config('GUI')

from django.contrib.auth import user_logged_out, user_logged_in
from django.dispatch import receiver

@receiver(user_logged_in)
def on_user_logged_in(sender, request, **kwargs):
    """trigger for user login"""
    LoggedInUser.objects.get_or_create(user=request.user)

@receiver(user_logged_out)
def on_user_logged_out(sender, request, **kwargs):
    """frees taken permissions on user logout"""

    if request.user.is_authenticated:
        LoggedInUser.objects.filter(user=request.user).delete()
    #pcas
    for pca in eca.pcaHandlers.items():
        pcaObject = pcaModel.objects.filter(id=pca[0]).get()
        if request.user.has_perm("has_pca_control",pcaObject):
         remove_perm('has_pca_control', request.user, pcaObject)
    #ecs
    ecsObject = ecsModel.objects.filter(id="ecs").get()
    if request.user.has_perm("has_ecs_control",ecsObject):
        remove_perm('has_ecs_control', request.user, ecsObject)

def permission_timeout():
    """remove permission has control if user has been inactive for a while"""
    while True:
        time.sleep(settings.PERMISSION_TIMEOUT)
        allPCAs = pcaModel.objects.all()
        #check for all pca
        for pcaObject in allPCAs:
            usersWithPermission = get_users_with_perms(pcaObject, attach_perms = True)
            for user, perms in usersWithPermission.items():
                if "has_pca_control" in perms:
                    timedelta = timezone.now() - pcaObject.permissionTimestamp
                    #check if there is a timeout
                    if timedelta.total_seconds() > settings.PERMISSION_TIMEOUT:
                        print(str(timedelta.total_seconds()) +" timeout user: "+str(user) )
                        remove_perm('has_pca_control', user, pcaObject)
                        #inform over websocket
                        eca.webSocket.permissionTimeout(str(user))
        #check for ecs
        ecsObject = ecsModel.objects.filter(id="ecs").get()
        usersWithPermission = get_users_with_perms(ecsObject, attach_perms = True)
        for user, perms in usersWithPermission.items():
            if "has_ecs_control" in perms:
                timedelta = timezone.now() - ecsObject.permissionTimestamp
                if timedelta.total_seconds() > settings.PERMISSION_TIMEOUT:
                    print(str(timedelta.total_seconds()) +" timeout user: "+str(user) )
                    remove_perm('has_ecs_control', user, ecsObject)
                    #inform over websocket
                    eca.webSocket.permissionTimeout(str(user))

t = threading.Thread(name="permission_timeout", target=permission_timeout)
t.start()

from django.views.generic import TemplateView,View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from guardian.mixins import PermissionRequiredMixin
class resetUserTimeoutMixin(object):
    """resets the timeout if a user makes a request"""
    def dispatch(self, request, *args, **kwargs):
        allPCAs = pcaModel.objects.all()
        for pcaObject in allPCAs:
            perm = get_user_perms(request.user,pcaObject)
            if 'has_pca_control' in perm:
                pcaObject.permissionTimestamp = timezone.now()
                pcaObject.save()
        ecsObject = ecsModel.objects.filter(id="ecs").get()
        perm = get_user_perms(request.user,ecsObject)
        if 'has_ecs_control' in perm:
            ecsObject.permissionTimestamp = timezone.now()
            ecsObject.save()
        return super().dispatch(request, *args, **kwargs)

class ecsMixin(LoginRequiredMixin,resetUserTimeoutMixin):
    """combination of Login required and reset timeout """
    partitions = eca.pcaHandlers.items()
    ecsObject = ecsModel.objects.filter(id="ecs").get()

class pcaForm(forms.Form):
    id = forms.CharField(label="id")
    address = forms.CharField(label="address")
    portPublish = forms.IntegerField(min_value= 1,label="Publish Port")
    portLog = forms.IntegerField(min_value= 1,label="Port Logmessages")
    portUpdates = forms.IntegerField(min_value= 1,label="Port Updates")
    portCurrentState = forms.IntegerField(min_value= 1,label="Port Current State")
    portCommand = forms.IntegerField(min_value= 1,label="Port Command")

class detectorForm(forms.Form):
    id = forms.CharField(label="id")
    address = forms.CharField(label="address")
    type = forms.CharField(label="type")
    portCommand = forms.IntegerField(min_value= 1,label="Port Command")

#views
class index(ecsMixin,TemplateView):
    template_name = "GUI/index.html"
    ecsMap = {}
    userInControl = None
    webSocketPort = settings.WEB_SOCKET_PORT

    def dispatch(self, request, *args, **kwargs):
        self.ecsMap = {}
        self.usersInPCAControl = {}
        for pca in eca.pcaHandlers.items():
            self.ecsMap[pca[0]] = pca[1].stateMap.map
            #get users who have control for PCA
            users = get_users_with_perms(pcaModel.objects.filter(id=pca[0]).get(), attach_perms = True)
            if len(users)>0:
                #there should only be at most one who is controlling partition/ecs
                user = list(users.keys())[0]
                if user == request.user:
                    self.usersInPCAControl[pca[0]] = "You"
                else:
                    self.usersInPCAControl[pca[0]]=user
            else:
                self.usersInPCAControl[pca[0]]=None
        self.ecsMap["unmapped"] = eca.unmappedDetectorController.statusMap.map
        #check if another user has control over ecs
        self.userInControl = None
        #get users who have control for ecs
        users = get_users_with_perms(self.ecsObject, attach_perms = True)
        if len(users)>0:
            #there should only be at most one who is controlling partition/ecs
            self.userInControl = list(users.keys())[0]
        if self.userInControl == request.user:
            self.userInControl = "You"
        if hasattr(request.user, 'logged_in_user'):
            self.sessionId = request.user.logged_in_user.session_key
        return super().dispatch(request, *args, **kwargs)

class pcaView(ecsMixin,TemplateView):
    template_name = "GUI/monitor.html"
    webSocketPort = settings.WEB_SOCKET_PORT

    def dispatch(self, request, *args, **kwargs):
        self.pcaId = self.kwargs['pcaId']
        self.pcaObject = pcaModel.objects.filter(id=self.pcaId).get()
        self.userInPCAControl = None
        usersWithPermission = get_users_with_perms(self.pcaObject, attach_perms = True)
        for user, perms in usersWithPermission.items():
            if "has_pca_control" in perms:
                self.userInPCAControl = user
                break
        if self.userInPCAControl == request.user:
            self.userInPCAControl = "You"

        self.userInECSControl = None
        usersWithPermission = get_users_with_perms(self.ecsObject, attach_perms = True)
        for user, perms in usersWithPermission.items():
            if "has_ecs_control" in perms:
                self.userInECSControl = user
                break
        if self.userInECSControl == request.user:
            self.userInECSControl = "You"
        if hasattr(request.user, 'logged_in_user'):
            self.sessionId = request.user.logged_in_user.session_key
        return super().dispatch(request, *args, **kwargs)

class ecsPermissionMixin(PermissionRequiredMixin):
    return_403 = True
    permission_required = 'has_ecs_control'
    permission_object = ecsModel.objects.filter(id="ecs").get()


class create_pca(ecsMixin,ecsPermissionMixin,FormView):
    #FormView
    template_name = 'GUI/ECS_Create_Partition.html'
    form_class = pcaForm
    success_url = '/'
    errorMessage = None

    raise_exception = True

    def form_valid(self, form):
        if not form.is_valid():
            return super().form_invalid(form)
        values = {
                "id" :  form.cleaned_data["id"],
                "address":  form.cleaned_data["address"],
                "portPublish" :  form.cleaned_data["portPublish"],
                "portLog" :  form.cleaned_data["portLog"],
                "portUpdates" :  form.cleaned_data["portUpdates"],
                "portCurrentState" :  form.cleaned_data["portCurrentState"],
                "portCommand" :  form.cleaned_data["portCommand"],
        }
        obj = partitionDataObject(values)
        ret = eca.createPartition(obj)
        if ret == True:
            return super().form_valid(form)
        else:
            self.errorMessage = ret
            return super().form_invalid(form)

class delete_pca(ecsMixin,ecsPermissionMixin,TemplateView):
    template_name = 'GUI/ECS_Delete_Partition.html'
    raise_exception = True

    def post(self, request, *args, **kwargs):
        partitions = request.POST.getlist("selectedPartitions")
        self.failedPartitions = False
        for pcaId in partitions:
            detectors = eca.database.getDetectorsForPartition(pcaId)
            self.forceDelete = False
            if "forceDelete" in request.POST:

Django/ECS_GUI/GUI/templates/GUI/ECS_Create_Detector.html
{% extends "GUI/base.html" %}
{% load widget_tweaks %}

{% block title %}
ECS Create Detector
{% endblock %}

{% block detectorActivity%}active{% endblock %}

{% block sideAndTopBar %}
  {{block.super}}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'GUI:index' %}">Overview</a>
  </li>
  <li class="breadcrumb-item active">Create Detector</li>
{% endblock %}

{% block content %}
  {% if view.errorMessage%}
    <div class="alert alert-danger" id="alertBox">
      <strong>Error: </strong><p>{{view.errorMessage}}</p>
    </div>
  {% endif %}
  <form action="{% url 'GUI:create_detector' %}" method="post">
    {% csrf_token %}
    {%for element in form%}
    <div class="form-group row">
      <label class="col-sm-1 col-form-label">{{element.label}}</label>
      {{element|add_class:"form-control col-sm-3"}}
    </div>
    {%endfor%}

    <input class="btn btn-primary" type="submit" value="Create new Detector">
  </form>
{% endblock content %}

Django/ECS_GUI/GUI/templates/GUI/ECS_Create_Partition.html
{% extends "GUI/base.html" %}
{% load widget_tweaks %}

{% block title %}
ECS Create Partition
{% endblock %}

{% block partitionActivity%}active{% endblock %}

{% block sideAndTopBar %}
  {{block.super}}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
      <a href="{% url 'GUI:index' %}">Overview</a>
    </li>
    <li class="breadcrumb-item active">Create Partition</li>
{% endblock %}

{% block content %}
{% if view.errorMessage%}
  <div class="alert alert-danger" id="alertBox">
    <strong>Error: </strong><p>{{view.errorMessage}}</p>
  </div>
{% endif %}
<form action="{% url 'GUI:create_pca' %}" method="post">
  {% csrf_token %}
  {%for element in form%}
  <div class="form-group row">
    <label class="col-sm-1 col-form-label">{{element.label}}</label>
    {{element|add_class:"form-control col-sm-3"}}
  </div>
  {%endfor%}

  <input class="btn btn-primary" type="submit" value="Create new Partition">
</form>
{% endblock content%}

Django/ECS_GUI/GUI/templates/GUI/ECS_Delete_Partition.html
{% extends "GUI/base.html" %}

{% block title %}
ECS Delete Partitions
{% endblock %}

{% block partitionActivity%}active{% endblock %}

{% block sideAndTopBar %}
  {{block.super}}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
      <a href="{% url 'GUI:index' %}">Overview</a>
    </li>
    <li class="breadcrumb-item active">Delete Partition</li>
{% endblock %}

{% block content %}
  {%if view.failedPartitions%}
  <div class="alert alert-danger" id="alertBox">
    <strong>error messages</strong><br/>
    {% for key,value in view.failedPartitions.items %}
      {%if value.0 == "unmapFail"%}
        <a>{{key}}: {{value.1}}</a><br/>
        {%for key,value in view.failedDetectors.items%}
          <a>{{key}}: {{value}}</a><br/>
        {%endfor%}
      {%else%}
        <a>{{key}}: {{value.1}}</a><br/>
      {%endif%}
    {% endfor %}
  </div>
  <form action="{% url 'GUI:delete_pca' %}" method="post">
    {% csrf_token %}
    <a>there had been errors while deleting some Partitions. Delete anyway?</a><br/>
    {% for p in view.failedPartitions %}
      <div class="form-check">
        <input type="checkbox" class="form-check-input" name='selectedPartitions' value="{{p}}" id="check{{p}}">
        <label class="form-check-label" for="check{{p}}">
          Partition {{p}}
        </label>
      </div>
    {% endfor %}
    <input type="hidden" name="forceDelete" value="True">
    <input class="btn btn-primary" type="submit" value="delete anyway">
  </form>
  {%else%}
  <form action="{% url 'GUI:delete_pca' %}" method="post">
    {% csrf_token %}
    {%for p in view.partitions%}
      <div class="form-check">
        <input type="checkbox" class="form-check-input" name='selectedPartitions' value="{{p.0}}" id="check{{p.0}}">
        <label class="form-check-label" for="check{{p.0}}">
          Partition {{p.0}}
        </label>
      </div>
    {%endfor%}
    <input class="btn btn-primary" type="submit" value="delete">
  </form>
  {%endif%}
{% endblock content %}

Django/ECS_GUI/GUI/templates/GUI/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv=”Pragma” content=”no-cache”>
    <meta http-equiv=”Expires” content=”-1″>
    <meta http-equiv=”CACHE-CONTROL” content=”NO-CACHE”>

    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'GUI/favicon.ico' %}"/>
    <!-- Bootstrap core CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'GUI/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Page level plugin CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'GUI/vendor/fontawesome-free/css/all.min.css' %}">
    <!-- Custom styles for this template-->
    <link href="{% static 'GUI/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'GUI/ecs.css' %}" rel="stylesheet">

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'GUI/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'GUI/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'GUI/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'GUI/scripts/sb-admin.js' %}"></script>
    {% block script %}
    {% endblock %}
  </head>
  {% load guardian_tags %}
  {% get_obj_perms request.user for view.ecsObject as "ecsPerms" %}
  <body id="page-top">
    {% block sideAndTopBar %}
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

      <a class="navbar-brand mr-1" href="{% url 'GUI:index'%}">Start ECS</a>

      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>

      <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <h5 class="dropdown-header">Logged in as {{user}}</h5>
            {% block control %}
            {% if perms.GUI.can_take_ecs_control %}
              {% if view.userInControl and view.userInControl != "You" %}
                <h5 class="dropdown-header">Control already Taken by User : {{view.userInControl}}</h5>
              {% endif %}
              {% if "has_ecs_control" in ecsPerms %}
                <h5 class="dropdown-header">You are currently controlling the ECS</h5>
                <a id="controlLink" class="dropdown-item" href="{% url 'GUI:giveup_ecs_control' 'ecs'%}">give up control of {{view.ecsObject}}</a>
              {% elif not view.userInControl %}
                <a id="controlLink" class="dropdown-item" href="{% url 'GUI:take_ecs_control' 'ecs'%}">take control of {{view.ecsObject}}</a>
              {% endif %}
              <div class="dropdown-divider"></div>
            {% endif %}
            {% endblock %}
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
      </ul>

    </nav>

    <div id="wrapper">

      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item {% block index%}{% endblock %}">
          <a class="nav-link" href="{% url 'GUI:index' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Overview</span>
          </a>
        </li>
        <li class="nav-item dropdown {% block pca%}{% endblock %}">
          <a class="nav-link dropdown-toggle" href="#" id="pcaDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-desktop"></i>
            <span>PCAs</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="pcaDropdown">
            {% for p in view.partitions %}
              <h6 class="dropdown-header">PCA <a href="{%url 'GUI:pca' p.1.id%}">{{p.1.id}}</a> </h6>
              {% if not forloop.last %}
                <div class="dropdown-divider"></div>
              {%endif%}
            {%endfor%}
          </div>
        </li>
        {% if "has_ecs_control" in ecsPerms %}
        <li class="nav-item dropdown {% block detectorActivity%}{% endblock %}">
          <a class="nav-link dropdown-toggle" href="#" id="detectorActDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-desktop"></i>
            <span>Detector Activities</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="detectorActDropdown">
            <a class="dropdown-item" href="{% url 'GUI:create_detector' %}">Create Detector</a>
            <a class="dropdown-item" href="{% url 'GUI:delete_detectors' %}">Delete Detector</a>
            <a class="dropdown-item" href="{% url 'GUI:move_detectors' %}">Move Detector</a>
          </div>
        </li>
        <li class="nav-item dropdown {% block partitionActivity%}{% endblock %}">
          <a class="nav-link dropdown-toggle" href="#" id="partitionActDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-desktop"></i>
            <span>Partition Activities</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="partitionActDropdown">
            <a class="dropdown-item" href="{% url 'GUI:create_pca' %}">Create Partition</a>
            <a class="dropdown-item" href="{% url 'GUI:delete_pca' %}">Delete Partition</a>
          </div>
        </li>
        <li class="nav-item dropdown {% block configActivity%}{% endblock %}">
          <a class="nav-link dropdown-toggle" href="#" id="configActDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-desktop"></i>
            <span>Configuration Activities</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="configActDropdown">
            <a class="dropdown-item" href="{% url 'GUI:editConfiguration' %}">Edit Configurations</a>
            <a class="dropdown-item" href="{% url 'GUI:editConfigurationTag' %}">Edit Tags</a>
          </div>
        </li>
        <li class="nav-item {% block clients%}{% endblock %}">
          <a class="nav-link" href="{% url 'GUI:clients' %}"  role="button" >
            <i class="fas fa-fw fa-desktop"></i>
            <span>Clients</span>
          </a>
        </li>
        {%endif%}
      </ul>
      <!-- Logout Modal-->
      {% if user.is_authenticated %}
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ user.get_username }}, ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
              <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'GUI:logout'%}">Logout</a>
              </div>
            </div>
          </div>
        </div>
      {% else %}
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="modal-body">Select "Login" below if you are ready to login.</div>
              <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'GUI:login'%}?next={{request.path}}">Login</a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
      {% endblock sideAndTopBar %}
      <div id="content-wrapper">

        <div class="container-fluid">
          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            {% block breadcrumb %}
            {% endblock %}
          </ol>
          <div class="alert alert-danger" id="alertBox" style="visibility: hidden"></div>
          {% block content %}
          {% endblock %}
      </div>
      <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->
  </body>
</html>

Django/ECS_GUI/GUI/templates/GUI/modal_base.html
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">{%block title%}{%endblock%}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% block body %}
    {% endblock %}
  </div>
  <div class="modal-footer">
    {%block footer%}
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    {%endblock%}
  </div>
</div>